### ISSUE TITLE
Standup 07/02/15

### ISSUE THREAD

**Issue by gatorpazz** [jorgehjr84/TIY-Upvote#25]
**Yesterday's work**
- Submit page scaffolding completed
- Questions page scaffolding completed
- 404 page scaffolding completed
- User page html skeleton completed
- Refactored main.js ($routeProvider config specifically)
- Created release/0.1.0--scaffolding branch
- added gulp-ng-annotate and ng-annotate as dependencies
- wired gulp-ng-annotate into gulpfile
- working gulp build and gulp serve:dist tasks
- npm installed firebase tools
- brainstormed basic data model

**Plans For Today**
- Finish Release Branch - deploy
- Planning for release/0.2.0
- Incorporate dummy data
- To be continued

**Blockers**
- Ng-annotate fix

**Comment by sjoyal** [comment]
@jorgehjr84 @pcreglow @gatorpazz @JessyRiordan @sjoyal
